Fix assertion problems in PeakStandardsAssigner/References
Adding row to the table causes:
```
org.eclipse.core.runtime.AssertionFailedException: assertion failed:
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:121)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:106)
	at org.eclipse.jface.viewers.TextCellEditor.doSetValue(TextCellEditor.java:225)
	at org.eclipse.jface.viewers.CellEditor.setValue(CellEditor.java:853)
	at org.eclipse.jface.viewers.EditingSupport.initializeCellEditorValue(EditingSupport.java:102)
	at org.eclipse.jface.viewers.ColumnViewerEditor.activateCellEditor(ColumnViewerEditor.java:203)
	at org.eclipse.jface.viewers.ColumnViewerEditor.handleEditorActivationEvent(ColumnViewerEditor.java:433)
	at org.eclipse.jface.viewers.ColumnViewer.triggerEditorActivationEvent(ColumnViewer.java:680)
	at org.eclipse.jface.viewers.ColumnViewer.handleMouseDown(ColumnViewer.java:655)
	at org.eclipse.jface.viewers.ColumnViewer$1.mouseDown(ColumnViewer.java:111)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5845)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1656)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4497)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:819)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.chemclipse.ux.extension.ui.methods.SettingsWizard.openEditPreferencesWizard(SettingsWizard.java:67)
	at org.eclipse.chemclipse.ux.extension.ui.methods.SettingsWizard.getSettings(SettingsWizard.java:127)
```

This is due to the fact that non-existing column was filtered so editing
support was added when it shouldn't.